add uv cache and secret check

diff --git a/.github/workflows/schedule_update.yml b/.github/workflows/schedule_update.yml
--- a/.github/workflows/schedule_update.yml
+++ b/.github/workflows/schedule_update.yml
@@ -15,8 +15,20 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
+    - name: Check Secrets
+      env:
+        SMU_ACCOUNT: ${{ secrets.SMU_ACCOUNT }}
+        SMU_PASSWORD: ${{ secrets.SMU_PASSWORD }}
+      run: |
+        if [ -z "$SMU_ACCOUNT" ] || [ -z "$SMU_PASSWORD" ]; then
+          echo "Error: SMU_ACCOUNT or SMU_PASSWORD secrets are not set."
+          exit 1
+        fi
+
     - name: Install uv
       uses: astral-sh/setup-uv@v3
+      with:
+        enable-cache: true
 
     - name: Set up Python
       run: uv python install
